CREATE TABLE `user` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `system_type` TINYINT NOT NULL DEFAULT 1 COMMENT '系统类型',
    `user_type` TINYINT DEFAULT 3 COMMENT '用户类型',
    `username` VARCHAR(255) COMMENT '用户名',
    `nick_name` VARCHAR(255) COMMENT '昵称',
    `real_name` VARCHAR(255) COMMENT '真实姓名',
    `avatar` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像URL',
    `avatar_update_time` TIMESTAMP(3) COMMENT '头像更新时间',
    `email` VARCHAR(255) COMMENT '邮箱地址',
    `region` VARCHAR(5) COMMENT '地区代码',
    `mobile` VARCHAR(11) COMMENT '手机号',
    `id_card` VARCHAR(18) COMMENT '身份证号',
    `wx_open_id` VARCHAR(255) COMMENT '微信OpenID',
    `dd_open_id` VARCHAR(255) COMMENT '钉钉OpenID',
    `sex` TINYINT DEFAULT 0 COMMENT '性别：0-未知，1-男，2-女',
    `state` TINYINT DEFAULT 1 COMMENT '状态：1-正常',
    `user_state_id` BIGINT COMMENT '用户状态ID',
    `resume` VARCHAR(200) COMMENT '简历',
    `work_describe` VARCHAR(255) COMMENT '工作描述',
    `item_id` BIGINT COMMENT '项目ID',
    `context` TINYINT DEFAULT 0 COMMENT '上下文',
    `num` BIGINT DEFAULT 10 COMMENT '数量',
    `password` VARCHAR(64) NOT NULL COMMENT '密码',
    `salt` VARCHAR(20) COMMENT '盐值',
    `password_error_num` INT DEFAULT 0 COMMENT '密码错误次数',
    `password_error_last_time` TIMESTAMP(3) COMMENT '密码错误最后时间',
    `password_expire_time` TIMESTAMP(3) COMMENT '密码过期时间',
    `last_opt_time` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '最后操作时间',
    `last_login_time` TIMESTAMP(3) COMMENT '最后登录时间',
    `ip_info` JSON COMMENT 'IP信息',
    `create_time` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `update_time` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    `create_by` BIGINT DEFAULT 1 COMMENT '创建人ID',
    `update_by` BIGINT COMMENT '更新人ID',
    `is_del` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
    `readonly` TINYINT DEFAULT 0 COMMENT '是否只读：0-否，1-是',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_email` (`email`)
) COMMENT '用户表';

CREATE INDEX `idx_user_username` ON `user` (`username`);
CREATE INDEX `idx_user_is_del` ON `user` (`is_del`);
